### ISSUE TITLE
Support SSO

### ISSUE THREAD

**Issue by croesnick** [croesnick/toniebox-audio-match#15]
Toniecloud enabled (and requires) SSO since September 1st. Well... this is something to be supported by toniebox-audio-match as well.

Relevant URLs:
* GET on https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth
```
curl 'https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth?client_id=meine-tonies&redirect_uri=<someuri>&state=<somestate>&response_mode=fragment&response_type=code&scope=openid&nonce=<somenonce>&kc_locale=de' 
  --compressed
```
* POST to https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/token

**Comment by mwinkler** [comment]
I also had to implement this today. Children become otherwise grumpy 😁.
Maybe it helps -> https://github.com/mwinkler/TonieBox.CreativeManager/blob/master/src/TonieCloud/TonieCloudClient.cs#L108

**Comment by croesnick** [comment]
Heyho @mwinkler! Many thanks for the great pointer! :) I finally found the time and, well, discipline to implement the fix. 🎊
